source = ~/.config/hypr/themes/mocha.conf
general {
	border_size = 1
	gaps_in = 5
	gaps_out = 5
	col.inactive_border = $overlay0
	col.active_border = $red
	layout = dwindle

	snap {
		enabled = true
		window_gap = 10
	}
}

decoration {
	rounding = 0
}

animations {
	enabled = true
	
	bezier = overshot, 0.05, 0.9, 0.1, 1.05
	bezier = smoothOut, 0.36, 0, 0.66, -0.56
	bezier = smoothIn, 0.25, 1, 0.5, 1
	
	animation = windows, 1, 2, overshot, slide
	animation = windowsOut, 1, 2, smoothOut, slide
	animation = windowsMove, 1, 2, default
	animation = border, 1, 10, default
	animation = borderangle, 1, 8, default
	animation = fade, 1, 7, smoothIn
	animation = fadeDim, 1, 7, smoothIn
	animation = workspaces, 1, 6, default, slidevert
}

input {
    numlock_by_default = true
}