source = ~/.config/hypr/vars.conf

# actual binds
bind = $mod, Q, exec, $terminal
bind = $mod, C, killactive
bind = $mod, R, exec, hyprctl reload
bind = $mod, SPACE, exec, $(tofi-drun -c ~/.config/tofi/config)
bind = $mod, E, exec, thunar

env = SLURP_ARGS, -c 00000000
bind = $mod, S, exec, grimblast --freeze copy area

bind = , PAGE_UP, pass, class:^(com\.obsproject\.Studio)$
bind = , PAGE_DOWN, pass, class:^(com\.obsproject\.Studio)$

# fullscreen toggle
bind = $mod, F, fullscreen

# mod leftclick = move
bindm = $mod, mouse:272, movewindow
# mod rightclick = resize
bindm = $mod, mouse:273, resizewindow

bind = $mod, left,  movewindow, l
bind = $mod, right, movewindow, r
bind = $mod, up,    movewindow, u
bind = $mod, down,  movewindow, d

# workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

